[tools]
"github:istio/istio[exe=istioctl]" = "1.21.6"
"aqua:kubernetes-sigs/kind"   = "0.31.0"
"aqua:kubernetes/kubectl"     = "1.35.4"
"aqua:tilt-dev/tilt"          = "0.37.1"
"aqua:tilt-dev/ctlptl"        = "0.9.2"
"aqua:jqlang/jq"              = "1.8.1"
"aqua:a8m/envsubst"           = "1.4.3"
