  FROM python:3.12-slim                                                                                                                                                                                              
                                                                                                                                                                                                                     
  RUN pip install 'spiffe-defakto[azure]'                                                                                                                                                                            
                                                                                                                                                                                                                     
  COPY main.py /main.py                                                                                                                                                                                              
                                                                                                                                                                                                                   
  CMD ["python", "/main.py"]
  